In [55]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))
# Prints "[1, 1, 2, 3, 6, 8, 10]"


[1, 1, 2, 3, 6, 8, 10]


# Basic data types
Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.
Numbers: Integers and floats work as you would expect from other languages:

In [56]:
x = 3
x
print(type(x))

<class 'int'>


In [57]:
print(x*2)
print(x**2, pow(x,2))
print(x/2)
print(x//2) # floored quotient of x and 2
print(x%2) 
divmod(x,2)

6
9 9
1.5
1
1


(1, 1)

In [58]:
y=2.5
y
print(type(y))
print(x,y,y+2)

<class 'float'>
3 2.5 4.5


In [59]:
print(abs(x))
print(int(y))

3
2


Note that unlike many languages, Python does not have unary increment ( x++ ) or decrement ( x-- ) operators.

## Complex Number

In [60]:
c=complex(2,2)
c.conjugate()

(2-2j)


## Booleans
Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols ( && , || , etc.):

In [61]:
t=False
f=True
print(type(f))
print(t and f)
print(not f)
print(t or f)
t != f # XOR

<class 'bool'>
False
False
True


True

## Strings

In [62]:
hello='hello'
world='world'
print(hello+' '+world)
hw = '%s %s  %s' % (hello,world,12) #sprintf style string format
print(hw)

hello world
hello world  12


In [63]:
print(hello.capitalize())
print(hello.upper())
print('%7s' % (hello))
print(hello.rjust(7))
print('%-7s' % (hello))
print(hello.ljust(7))

Hello
HELLO
  hello
  hello
hello  
hello  


In [64]:
print(hello.replace('l','(ell)'))

he(ell)(ell)o


In [65]:
print('  world'.strip())

world


# Containers
lists, dictionaries, sets, and tuples.


## Lists
A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [66]:
xs=[3,1,2]
print(xs,xs[2],xs[-1])

xs[2]='foo' # lists can contain elements of different types
print(xs)
xs.append('bar')
print(xs)
x=xs.pop() # remove and return the last
print(x,xs)

[3, 1, 2] 2 2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']



## Slicing
In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [67]:
nums=list(range(5))
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:4])
print(nums[:])
print(nums[:-1])

nums[2:4]=[8,9]
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


## Loops
You can loop over the elements of a list like this:

In [68]:
for num in nums:
    print(num)
print(nums)

0
1
8
9
4
[0, 1, 8, 9, 4]


In [69]:
for id,num in enumerate(nums): #index
    print(id+1,num)
print(nums)

1 0
2 1
3 8
4 9
5 4
[0, 1, 8, 9, 4]


## List comprehensions
When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:


In [70]:
nums=[0,1,2,3,4]
squares=[]
for x in nums:
    squares.append(x**2)
print(squares)

[0, 1, 4, 9, 16]


In [71]:
nums=[0,1,2,3,4]
squares=[x**2 for x in nums]
print(squares)

even_squares=[x**2 for x in nums if x%2==0]
print(even_squares)

[0, 1, 4, 9, 16]
[0, 4, 16]


## Dictionaries
A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:

In [72]:
dic =dict()
dic={'cat':'cute','dog':'furry'}
print(dic['cat'])
print(dic.get('cat','N/A'))
print(dic.get('dic','N/A'))
print('dic' in dic) # check if a dictionary has a key 
print('cat' in dic) 
del dic['cat']

cute
cute
N/A
False
True


## Loops
It is easy to iterate over the keys in a dictionary:

In [73]:
dic={'cat':'cute','dog':'furry'}
for animal in dic: # key
    print(animal,dic[animal])

cat cute
dog furry


In [74]:
dic={'cat':'cute','dog':'furry'}
for animal,adj in dic.items(): # keys and values
    print(animal,adj)

cat cute
dog furry


## Dictionary comprehensions
These are similar to list comprehensions, but allow you to easily construct dictionaries.

In [75]:
nums=[0,1,2,3,4]
even_num_square={x:x**2 for x in nums if x % 2==0 }
print(even_num_square)

{0: 0, 2: 4, 4: 16}


## Sets
A set is an unordered collection of distinct elements.


In [76]:
animals=set()
animals={'cat','dog'}
print('cat' in animals)
animals.add('fish')
print(len(animals))
animals.remove('cat')

True
3


### Loops
Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [77]:
for id,animal in enumerate(animals):
    print("#%d: %s"% (id+1,animal))

#1: fish
#2: dog


## Set comprehensions
Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [78]:
nums={x**2 for x in range(20)}
print(nums)

{0, 1, 256, 4, 9, 16, 144, 25, 289, 36, 169, 49, 64, 196, 324, 81, 225, 100, 361, 121}


# Tuples
A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [79]:
d=tuple()
d={(x,x+1):x for x in range(10)}
print(d)
print(type((5,6)))
d[(5,6)]

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
<class 'tuple'>


5

# Functions
Python functions are defined using the def keyword

In [80]:
def sign(x):
    if x>0 :
        return 'positive'
    elif x<0 :
        return 'negative'
    else:
        return 'zero'
for x in [-1,0,-1]:
    print(sign(x))

negative
zero
negative


We will often define functions to take optional keyword arguments, like this:

In [83]:
def hello(name,loud=False):
    if loud:
        print('Hello, %s!' % name.upper())
    else:
        print('Hello, %s!' % name)
hello('Bob')
hello('Jack',loud=True)

Hello, Bob!
Hello, JACK!


# Classes


In [85]:
class Greeter(object):
    def __init__(self,name) -> None:
        self.name=name
    def greet(self,loud=False):
        if loud:
            print('Hello, %s!' % self.name.upper())
        else:
            print('Hello, %s!' % self.name)
g=Greeter('Fred')
g.greet()
g.greet(True)


Hello, Fred!
Hello, FRED!


# Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.
We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [89]:
import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a)

<class 'numpy.ndarray'>
(3,)
[1 2 3]


In [91]:
b=np.array([[1,2,3],[4,5,6]]) # list of list
print(b.shape)
print(b[0,0])

(2, 3)
1


In [99]:
a=np.zeros((2,2))
print(a)

b=np.ones((1,2))
print(b)

c=np.full((2,2),7)
print(c)

d=np.eye(2) # Identity matrix
print(d)

e=np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.92670626 0.58350025]
 [0.91285984 0.10470932]]


## Array indexing
### Slicing
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [105]:
a=np.array([[1,2,3,4],[2,3,5,6]])
print(a)
print(a[:2,1:3]) # row col
print(a[:,1:3])

[[1 2 3 4]
 [2 3 5 6]]
[[2 3]
 [3 5]]
[[2 3]
 [3 5]]


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [108]:
print(a[1,1:3])
print(a[1,1:3].shape)

[3 5]
(2,)


## Integer array indexing
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array.  \
In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [117]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]]) # row col
print(np.array([a[0,0],a[1,1],a[2,0]]))
print(a[[0,0,0],[1,1,1]])

[1 4 5]
[1 4 5]
[2 2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [121]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

b=np.array([0,2,0,1])

print(a[np.arange(4),b])

a[np.arange(4),b]+=10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


## Boolean array indexing
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [124]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
bool_idx =(a>2)
print(bool_idx)
print(a[bool_idx]) # rank 1
print(a[a>2])

[[False False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[ 3  4  5  6  7  8  9 10 11 12]
[ 3  4  5  6  7  8  9 10 11 12]


## Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [128]:
x=np.array([1,2])
print(x.dtype)

x=np.array([1.0,2.0])
print(x.dtype)

x=np.array([1,2],dtype=np.int16)
print(x.dtype)

int64
float64
int16


## Array math


In [141]:
x = np.array([1,2])
y= np.array([3,4])
print(x+y,np.add(x,y))
print(x-y, np.subtract(x,y))
print(x*y,np.multiply(x,y)) #element wise
print(x/y, np.divide(x,y))
print(np.sqrt(x))

print(x.dot(y), np.dot(x,y)) # matrix, vector multiplication

print(np.sum(x))
num=[1,2]
print(sum(num))
x=np.array([[1,2],[3,4]])
print(np.sum(x,axis=0)) # each col / along with row 
print(np.sum(x,axis=1)) # each row / along with col

print(x.T)

[4 6] [4 6]
[-2 -2] [-2 -2]
[3 8] [3 8]
[0.33333333 0.5       ] [0.33333333 0.5       ]
[1.         1.41421356]
11 11
3
3
[4 6]
[3 7]
[[1 3]
 [2 4]]
